<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
$target = $block->getTarget();
$label = $block->getLabel();
?>

<a class="logo">
        <img src="http://192.168.0.71/pub/static/frontend/angeldm/optimus/es_ES/images/logo.png" alt="Magento Commerce" width="148" height="43">
</a>

<a class="action skip <?php /* @escapeNotVerified */ echo $target?>" href="#<?php /* @escapeNotVerified */ echo $target?>"><span><?php /* @escapeNotVerified */ echo $label ?></span></a>
